### PR TITLE
Add basic gif rendering functionality

### PR DESCRIPTION
**Pull request by giantballofyarn**
#### Add basic gif capture/render functionality

Output
test3

Controls hack
image

#### Library used / credits to
- https://github.com/jnordberg/gif.js

### CODE REVIEW

**Comment by zz85** [comment]
Nice work @giantballofyarn!

Just some suggestions - I would not make gifProcess part of GUI because it's an informative rather than an actionable slider. Also, instead of opening the gif in a new window (which gets block by the browser), I would create a link.

Would you like to update this PR? Otherwise I could merge and work on those changes later.

**Comment by giantballofyarn** [comment]
👌 will update this

**Comment by giantballofyarn** [comment]
Moved gif status to bottom centre of page with the following UI:
image
image
image

@zz85

**Comment by zz85** [comment]
Looks great. Thanks @giantballofyarn!

**Pull request merged**
